{% set name = "cwlformat" %}
{% set version = "2022.02.18" %}
{% set sha256 = "05800a7766f8fceef55c513952ddc1516e4d378e752f487c50379c923b930539" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rabix/cwl-format/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cwl-format=cwlformat.formatter:main
    - cwl-explode=cwlformat.explode:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ruamel.yaml

test:
  imports:
    - cwlformat
    - cwlformat.formatter
    - cwlformat.explode
  commands:
    - cwl-format --help
    - cwl-explode --help

about:
  home: https://github.com/rabix/cwl-format
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A very opinionated code formatter for CWL '
  description: |
    CWL Format is a specification and a reference implementation for a very 
    opinionated CWL code formatter.

    It outputs CWL in a standardized YAML format. It has no settings or options 
    because you have better things to do with your time. And because CWL Format
    is always correct.

extra:
  recipe-maintainers:
    - pvanheus
